-- This removes all existing Central Library tables and data.

SET SERVEROUTPUT ON;
SET DEFINE OFF;
WHENEVER SQLERROR CONTINUE;

DROP VIEW overdue_report;
DROP VIEW inventory_report;

DROP PROCEDURE create_overdue_notices;
DROP PROCEDURE return_book;
DROP PROCEDURE issue_book;
DROP FUNCTION calculate_fine;

DROP TABLE fines CASCADE CONSTRAINTS PURGE;
DROP TABLE reservations CASCADE CONSTRAINTS PURGE;
DROP TABLE issue_transactions CASCADE CONSTRAINTS PURGE;
DROP TABLE book_copies CASCADE CONSTRAINTS PURGE;
DROP TABLE book_details CASCADE CONSTRAINTS PURGE;
DROP TABLE books CASCADE CONSTRAINTS PURGE;
DROP TABLE branches CASCADE CONSTRAINTS PURGE;
DROP TABLE notifications CASCADE CONSTRAINTS PURGE;
DROP TABLE failed_jobs CASCADE CONSTRAINTS PURGE;
DROP TABLE job_batches CASCADE CONSTRAINTS PURGE;
DROP TABLE jobs CASCADE CONSTRAINTS PURGE;
DROP TABLE cache_locks CASCADE CONSTRAINTS PURGE;
DROP TABLE cache CASCADE CONSTRAINTS PURGE;
DROP TABLE sessions CASCADE CONSTRAINTS PURGE;
DROP TABLE users CASCADE CONSTRAINTS PURGE;
DROP TABLE roles CASCADE CONSTRAINTS PURGE;
DROP TABLE migrations CASCADE CONSTRAINTS PURGE;

DROP SEQUENCE fines_seq;
DROP SEQUENCE reservations_seq;
DROP SEQUENCE issues_seq;
DROP SEQUENCE issue_transactions_seq;
DROP SEQUENCE book_copies_seq;
DROP SEQUENCE book_details_seq;
DROP SEQUENCE books_seq;
DROP SEQUENCE branches_seq;
DROP SEQUENCE notifications_seq;
DROP SEQUENCE failed_jobs_seq;
DROP SEQUENCE jobs_seq;
DROP SEQUENCE sessions_seq;
DROP SEQUENCE users_seq;
DROP SEQUENCE roles_seq;

WHENEVER SQLERROR EXIT SQL.SQLCODE;
@@schema.sql
